name: C/C++ CI

on:
  push:
    branches: [ v0.5 ]
  pull_request:
    branches: [ v0.5 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Hivatalos ARM GCC 9-2020-q2 letöltése és PATH-hoz adása (Node-független)
    - name: Set up arm-none-eabi-gcc (9-2020-q2)
      run: |
        wget -q https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2020q2/gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
        tar -xjf gcc-arm-none-eabi-9-2020-q2-update-x86_64-linux.tar.bz2
        echo "$GITHUB_WORKSPACE/gcc-arm-none-eabi-9-2020-q2-update/bin" >> $GITHUB_PATH

    - name: Build project
      run: make

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Prepare ZIP
      run: python tools/xiaotea/Scripts/prepareZip_online.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: ${{ github.workspace }}/tools/zip_output
        name: M365_v3_build_${{ github.run_number }}
        retention-days: 5
