name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Kényszerítjük a Node.js 24 használatát a figyelmeztetés eltüntetéséhez
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up arm-none-eabi-gcc
      uses: fiam/arm-none-eabi-gcc@v1.0.2
      with:
        release: '9-2020-q2'

    # EZ A JAVÍTÁS: Manuálisan hozzáadjuk a GCC-t az elérési úthoz az új módszerrel
    - name: Fix GCC Path
      run: echo "/home/runner/.arm-none-eabi-gcc/bin" >> $GITHUB_PATH

    - name: Build project
      run: make
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Prepare ZIP
      run: python tools/xiaotea/Scripts/prepareZip_online.py      
      
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        path: ${{ github.workspace }}/tools/zip_output
        name: M365_v3_build_${{ github.run_number }}
        retention-days: 5
